export const CONSTELLATION_PL: Array<{ value: string; label: string }> = [
  { value: 'And', label: 'Andromeda' },
  { value: 'Ari', label: 'Baran' },
  { value: 'Gem', label: 'Bliźnięta' },
  { value: 'Tau', label: 'Byk' },
  { value: 'Cep', label: 'Cefeusz' },
  { value: 'Cen', label: 'Centaur' },
  { value: 'Cir', label: 'Cyrkiel' },
  { value: 'Del', label: 'Delfin' },
  { value: 'Eri', label: 'Erydan' },
  { value: 'Phe', label: 'Feniks' },
  { value: 'Col', label: 'Gołąb' },
  { value: 'Her', label: 'Herkules' },
  { value: 'Hya', label: 'Hydra' },
  { value: 'Ind', label: 'Indianin' },
  { value: 'Lac', label: 'Jaszczurka' },
  { value: 'Mon', label: 'Jednorożec' },
  { value: 'Cha', label: 'Kameleon' },
  { value: 'Cas', label: 'Kasjopea' },
  { value: 'Car', label: 'Kil' },
  { value: 'Pyx', label: 'Kompas' },
  { value: 'CrA', label: 'Korona Południowa' },
  { value: 'CrB', label: 'Korona Północna' },
  { value: 'Cap', label: 'Koziorożec' },
  { value: 'Crv', label: 'Kruk' },
  { value: 'Cru', label: 'Krzyż Południa' },
  { value: 'Leo', label: 'Lew' },
  { value: 'Vul', label: 'Lisek' },
  { value: 'Tel', label: 'Luneta' },
  { value: 'Lyr', label: 'Lutnia' },
  { value: 'Cyg', label: 'Łabędź' },
  { value: 'UMi', label: 'Mała Niedźwiedzica' },
  { value: 'Pic', label: 'Malarz' },
  { value: 'LMi', label: 'Mały Lew' },
  { value: 'CMi', label: 'Mały Pies' },
  { value: 'Mic', label: 'Mikroskop' },
  { value: 'Mus', label: 'Mucha' },
  { value: 'Oct', label: 'Oktant' },
  { value: 'Ara', label: 'Ołtarz' },
  { value: 'Ori', label: 'Orion' },
  { value: 'Aql', label: 'Orzeł' },
  { value: 'Vir', label: 'Panna' },
  { value: 'Pav', label: 'Paw' },
  { value: 'Peg', label: 'Pegaz' },
  { value: 'Per', label: 'Perseusz' },
  { value: 'For', label: 'Piec' },
  { value: 'Ant', label: 'Pompa' },
  { value: 'CVn', label: 'Psy Gończe' },
  { value: 'Aps', label: 'Ptak Rajski' },
  { value: 'Crt', label: 'Puchar' },
  { value: 'Cnc', label: 'Rak' },
  { value: 'Ret', label: 'Sieć' },
  { value: 'Pup', label: 'Rufa' },
  { value: 'Vol', label: 'Ryba Latająca' },
  { value: 'PsA', label: 'Ryba Południowa' },
  { value: 'Psc', label: 'Ryby' },
  { value: 'Cae', label: 'Rylec' },
  { value: 'Lyn', label: 'Ryś' },
  { value: 'Scl', label: 'Rzeźbiarz' },
  { value: 'Sco', label: 'Skorpion' },
  { value: 'Dra', label: 'Smok' },
  { value: 'Men', label: 'Stół' },
  { value: 'Sex', label: 'Sekstant' },
  { value: 'Sge', label: 'Strzała' },
  { value: 'Sgr', label: 'Strzelec' },
  { value: 'Sct', label: 'Tarcza' },
  { value: 'Tri', label: 'Trójkąt' },
  { value: 'TrA', label: 'Trójkąt Południowy' },
  { value: 'Tuc', label: 'Tukan' },
  { value: 'Lib', label: 'Waga' },
  { value: 'Com', label: 'Warkocz Bereniki' },
  { value: 'Ser', label: 'Wąż' },
  { value: 'Hyi', label: 'Wąż Wodny' },
  { value: 'Nor', label: 'Węgielnica' },
  { value: 'Oph', label: 'Wężownik' },
  { value: 'UMa', label: 'Wielka Niedźwiedzica' },
  { value: 'CMa', label: 'Wielki Pies' },
  { value: 'Cet', label: 'Wieloryb' },
  { value: 'Lup', label: 'Wilk' },
  { value: 'Aqr', label: 'Wodnik' },
  { value: 'Boo', label: 'Wolarz' },
  { value: 'Aur', label: 'Woźnica' },
  { value: 'Lep', label: 'Zając' },
  { value: 'Hor', label: 'Zegar' },
  { value: 'Dor', label: 'Złota Ryba' },
  { value: 'Equ', label: 'Źrebię' },
  { value: 'Vel', label: 'Żagle' },
  { value: 'Gru', label: 'Żuraw' },
  { value: 'Cam', label: 'Żyrafa' },
];
